# Generated by Django 4.1.2 on 2023-03-16 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='PositionJob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.positionjob', verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='login',
            field=models.CharField(default=1, max_length=100, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=1, max_length=100, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.URLField(default=1, verbose_name='Ссылка на фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.employee', verbose_name='Работник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.status', verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
